
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace nfirestore_cli {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    
    
    public partial class DatabaseSelector : Terminal.Gui.Dialog {
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.TextField tfProject;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.TextField tfDatabase;
        
        private Terminal.Gui.Label label3;
        
        private Terminal.Gui.TextField tfEmulator;
        
        private Terminal.Gui.Label label4;
        
        private Terminal.Gui.Button btnOk;
        
        private Terminal.Gui.Button btnTest;
        
        private Terminal.Gui.Button btnExit;
        
        private void InitializeComponent() {
            this.btnExit = new Terminal.Gui.Button();
            this.btnTest = new Terminal.Gui.Button();
            this.btnOk = new Terminal.Gui.Button();
            this.label4 = new Terminal.Gui.Label();
            this.tfEmulator = new Terminal.Gui.TextField();
            this.label3 = new Terminal.Gui.Label();
            this.tfDatabase = new Terminal.Gui.TextField();
            this.label2 = new Terminal.Gui.Label();
            this.tfProject = new Terminal.Gui.TextField();
            this.label = new Terminal.Gui.Label();
            this.Width = Dim.Percent(65f);
            this.Height = 12;
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Modal = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.Title = "Firestore Database Chooser";
            this.label.Width = 4;
            this.label.Height = 1;
            this.label.X = 1;
            this.label.Y = 1;
            this.label.Visible = true;
            this.label.Data = "label";
            this.label.Text = "Project:";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label);
            this.tfProject.Width = Dim.Fill(1);
            this.tfProject.Height = 1;
            this.tfProject.X = 15;
            this.tfProject.Y = 1;
            this.tfProject.Visible = true;
            this.tfProject.Secret = false;
            this.tfProject.Data = "tfProject";
            this.tfProject.Text = "";
            this.tfProject.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.tfProject);
            this.label2.Width = 4;
            this.label2.Height = 1;
            this.label2.X = 1;
            this.label2.Y = 3;
            this.label2.Visible = true;
            this.label2.Data = "label2";
            this.label2.Text = "Database:";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label2);
            this.tfDatabase.Width = Dim.Fill(1);
            this.tfDatabase.Height = 1;
            this.tfDatabase.X = 15;
            this.tfDatabase.Y = 3;
            this.tfDatabase.Visible = true;
            this.tfDatabase.Secret = false;
            this.tfDatabase.Data = "tfDatabase";
            this.tfDatabase.Text = "<default>";
            this.tfDatabase.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.tfDatabase);
            this.label3.Width = 4;
            this.label3.Height = 1;
            this.label3.X = 1;
            this.label3.Y = 5;
            this.label3.Visible = true;
            this.label3.Data = "label3";
            this.label3.Text = "Emulator Url:";
            this.label3.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label3);
            this.tfEmulator.Width = Dim.Fill(1);
            this.tfEmulator.Height = 1;
            this.tfEmulator.X = 15;
            this.tfEmulator.Y = 5;
            this.tfEmulator.Visible = true;
            this.tfEmulator.Secret = false;
            this.tfEmulator.Data = "tfEmulator";
            this.tfEmulator.Text = "";
            this.tfEmulator.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.tfEmulator);
            this.label4.Width = 4;
            this.label4.Height = 1;
            this.label4.X = 24;
            this.label4.Y = 6;
            this.label4.Visible = true;
            this.label4.Data = "label4";
            this.label4.Text = "(Leave blank for production)";
            this.label4.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label4);
            this.btnOk.Width = 8;
            this.btnOk.Height = 1;
            this.btnOk.X = 14;
            this.btnOk.Y = 8;
            this.btnOk.Visible = true;
            this.btnOk.Data = "btnOk";
            this.btnOk.Text = "Ok";
            this.btnOk.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnOk.IsDefault = true;
            this.Add(this.btnOk);
            this.btnTest.Width = 8;
            this.btnTest.Height = 1;
            this.btnTest.X = 32;
            this.btnTest.Y = 8;
            this.btnTest.Visible = true;
            this.btnTest.Data = "btnTest";
            this.btnTest.Text = "Test";
            this.btnTest.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnTest.IsDefault = false;
            this.Add(this.btnTest);
            this.btnExit.Width = 8;
            this.btnExit.Height = 1;
            this.btnExit.X = 52;
            this.btnExit.Y = 8;
            this.btnExit.Visible = true;
            this.btnExit.Data = "btnExit";
            this.btnExit.Text = "Exit";
            this.btnExit.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnExit.IsDefault = false;
            this.Add(this.btnExit);
        }
    }
}
