
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace nfirestore_cli {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    
    
    public partial class DatabaseSelector : Terminal.Gui.Dialog {
        
        private Terminal.Gui.ColorScheme redOnBlack;
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.TextField tfProject;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.TextField tfDatabase;
        
        private Terminal.Gui.Label label3;
        
        private Terminal.Gui.TextField tfEmulator;
        
        private Terminal.Gui.Label label4;
        
        private Terminal.Gui.Label label5;
        
        private Terminal.Gui.TextField tfMaxResults;
        
        private Terminal.Gui.Label label6;
        
        private Terminal.Gui.Button btnOk;
        
        private Terminal.Gui.Button btnTest;
        
        private Terminal.Gui.SpinnerView spinnerView;
        
        private Terminal.Gui.Button btnExit;
        
        private Terminal.Gui.Label lblError;
        
        private Terminal.Gui.Label lblSuccess;
        
        private void InitializeComponent() {
            this.lblSuccess = new Terminal.Gui.Label();
            this.lblError = new Terminal.Gui.Label();
            this.btnExit = new Terminal.Gui.Button();
            this.spinnerView = new Terminal.Gui.SpinnerView();
            this.btnTest = new Terminal.Gui.Button();
            this.btnOk = new Terminal.Gui.Button();
            this.label6 = new Terminal.Gui.Label();
            this.tfMaxResults = new Terminal.Gui.TextField();
            this.label5 = new Terminal.Gui.Label();
            this.label4 = new Terminal.Gui.Label();
            this.tfEmulator = new Terminal.Gui.TextField();
            this.label3 = new Terminal.Gui.Label();
            this.tfDatabase = new Terminal.Gui.TextField();
            this.label2 = new Terminal.Gui.Label();
            this.tfProject = new Terminal.Gui.TextField();
            this.label = new Terminal.Gui.Label();
            this.redOnBlack = new Terminal.Gui.ColorScheme(
                new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Black),
                new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Yellow),
                new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Black),
                new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black),
                new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Yellow)
            );
            this.greenOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4279476494u, 4278979596u), new Terminal.Gui.Attribute(4279476494u, 4287109016u), new Terminal.Gui.Attribute(4279682572u, 4278979596u), new Terminal.Gui.Attribute(4291611852u, 4278979596u), new Terminal.Gui.Attribute(4279682572u, 4287109016u));
            this.Width = Dim.Fill();
            this.Height = 16;
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Modal = true;
            this.TextAlignment = Terminal.Gui.Alignment.Center;
            this.Title = "Firestore Database Chooser";
            this.label.Width = 4;
            this.label.Height = 1;
            this.label.X = 1;
            this.label.Y = 1;
            this.label.Visible = true;
            this.label.Data = "label";
            this.label.Text = "Project:";
            this.label.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label);
            this.tfProject.Width = Dim.Fill(1);
            this.tfProject.Height = 1;
            this.tfProject.X = 15;
            this.tfProject.Y = 1;
            this.tfProject.Visible = true;
            this.tfProject.Secret = false;
            this.tfProject.Data = "tfProject";
            this.tfProject.Text = "";
            this.tfProject.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.tfProject);
            this.label2.Width = 4;
            this.label2.Height = 1;
            this.label2.X = 1;
            this.label2.Y = 3;
            this.label2.Visible = true;
            this.label2.Data = "label2";
            this.label2.Text = "Database:";
            this.label2.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label2);
            this.tfDatabase.Width = Dim.Fill(1);
            this.tfDatabase.Height = 1;
            this.tfDatabase.X = 15;
            this.tfDatabase.Y = 3;
            this.tfDatabase.Visible = true;
            this.tfDatabase.Secret = false;
            this.tfDatabase.Data = "tfDatabase";
            this.tfDatabase.Text = "<default>";
            this.tfDatabase.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.tfDatabase);
            this.label3.Width = 4;
            this.label3.Height = 1;
            this.label3.X = 1;
            this.label3.Y = 5;
            this.label3.Visible = true;
            this.label3.Data = "label3";
            this.label3.Text = "Emulator Url:";
            this.label3.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label3);
            this.tfEmulator.Width = Dim.Fill(1);
            this.tfEmulator.Height = 1;
            this.tfEmulator.X = 15;
            this.tfEmulator.Y = 5;
            this.tfEmulator.Visible = true;
            this.tfEmulator.Secret = false;
            this.tfEmulator.Data = "tfEmulator";
            this.tfEmulator.Text = "";
            this.tfEmulator.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.tfEmulator);
            this.label4.Width = 4;
            this.label4.Height = 1;
            this.label4.X = 0;
            this.label4.Y = 6;
            this.label4.Visible = true;
            this.label4.Data = "label4";
            this.label4.Text = "(Leave blank for production)";
            this.label4.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label4);
            this.label5.Width = 4;
            this.label5.Height = 1;
            this.label5.X = 2;
            this.label5.Y = 7;
            this.label5.Visible = true;
            this.label5.Data = "label5";
            this.label5.Text = "Max Results:";
            this.label5.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label5);
            this.tfMaxResults.Width = Dim.Fill(1);
            this.tfMaxResults.Height = 1;
            this.tfMaxResults.X = 15;
            this.tfMaxResults.Y = 7;
            this.tfMaxResults.Visible = true;
            this.tfMaxResults.Secret = false;
            this.tfMaxResults.Data = "tfMaxResults";
            this.tfMaxResults.Text = "";
            this.tfMaxResults.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.tfMaxResults);
            this.label6.Width = 4;
            this.label6.Height = 1;
            this.label6.X = 0;
            this.label6.Y = 8;
            this.label6.Visible = true;
            this.label6.Data = "label6";
            this.label6.Text = "(Maximum number of documents to request in any single query)";
            this.label6.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.label6);
            this.btnOk.Width = 8;
            this.btnOk.Height = 1;
            this.btnOk.X = 14;
            this.btnOk.Y = 10;
            this.btnOk.Visible = true;
            this.btnOk.Data = "btnOk";
            this.btnOk.Text = "Ok";
            this.btnOk.TextAlignment = Terminal.Gui.Alignment.Center;
            this.btnOk.IsDefault = true;
            this.Add(this.btnOk);
            this.btnTest.Width = 8;
            this.btnTest.Height = 1;
            this.btnTest.X = 32;
            this.btnTest.Y = 10;
            this.btnTest.Visible = true;
            this.btnTest.Data = "btnTest";
            this.btnTest.Text = "Test";
            this.btnTest.TextAlignment = Terminal.Gui.Alignment.Center;
            this.btnTest.IsDefault = false;
            this.Add(this.btnTest);
            this.spinnerView.Width = 1;
            this.spinnerView.Height = 1;
            this.spinnerView.X = 41;
            this.spinnerView.Y = 10;
            this.spinnerView.Visible = true;
            this.spinnerView.AutoSpin = true;
            this.spinnerView.Style = new Terminal.Gui.SpinnerStyle.Line();
            this.spinnerView.Data = "spinnerView";
            this.spinnerView.Text = "/";
            this.spinnerView.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.spinnerView);
            this.btnExit.Width = 8;
            this.btnExit.Height = 1;
            this.btnExit.X = 52;
            this.btnExit.Y = 10;
            this.btnExit.Visible = true;
            this.btnExit.Data = "btnExit";
            this.btnExit.Text = "Exit";
            this.btnExit.TextAlignment = Terminal.Gui.Alignment.Center;
            this.btnExit.IsDefault = false;
            this.Add(this.btnExit);
            this.lblError.Width = Dim.Fill(0);
            this.lblError.Height = Dim.Fill(0);
            this.lblError.X = 0;
            this.lblError.Y = 11;
            this.lblError.Visible = false;
            this.lblError.ColorScheme = this.redOnBlack;
            this.lblError.Data = "lblError";
            this.lblError.Text = "lblTestResults";
            this.Add(this.lblError);
            this.lblSuccess.Width = Dim.Fill(0);
            this.lblSuccess.Height = Dim.Fill(0);
            this.lblSuccess.X = 0;
            this.lblSuccess.Y = 11;
            this.lblSuccess.Visible = false;
            this.lblSuccess.ColorScheme = this.greenOnBlack;
            this.lblSuccess.Data = "lblSuccess";
            this.lblSuccess.Text = "lblSuccess";
            this.Add(this.lblSuccess);
        }
    }
}
