
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace nfirestore_cli {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class MainWindow : Terminal.Gui.Toplevel {
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.MenuBar menuBar;
        
        private Terminal.Gui.MenuBarItem fileF9Menu;
        
        private Terminal.Gui.MenuItem saveAsMenuItem;
        
        private Terminal.Gui.MenuItem refreshMenuItem;
        
        private Terminal.Gui.MenuItem exitMenuItem;
        
        private Terminal.Gui.MenuBarItem testMenu;
        
        private Terminal.Gui.MenuItem createTestDocumentsMenuItem;
        
        private Terminal.Gui.MenuItem createTestNestedDocumentsMenuItem;
        
        private void InitializeComponent() {
            this.menuBar = new Terminal.Gui.MenuBar();

            this.tgDefault = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4294967295u, 4278190335u), new Terminal.Gui.Attribute(4278190080u, 4286611584u), new Terminal.Gui.Attribute(4284602070u, 4278190335u), new Terminal.Gui.Attribute(4294967040u, 4278190335u), new Terminal.Gui.Attribute(4282087679u, 4286611584u));

            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewArrangement.Overlapped;
            this.ColorScheme = this.tgDefault;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = 1;
            this.menuBar.X = 0;
            this.menuBar.Y = 0;
            this.menuBar.Visible = true;
            this.menuBar.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.menuBar.CanFocus = false;
            this.menuBar.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.Alignment.Start;
            this.fileF9Menu = new Terminal.Gui.MenuBarItem();
            this.fileF9Menu.Title = "_File (F9)";
            this.saveAsMenuItem = new Terminal.Gui.MenuItem();
            this.saveAsMenuItem.Title = "Save As...";
            this.saveAsMenuItem.Data = "saveAsMenuItem";
            this.refreshMenuItem = new Terminal.Gui.MenuItem();
            this.refreshMenuItem.Title = "_Refresh";
            this.refreshMenuItem.Data = "refreshMenuItem";
            this.exitMenuItem = new Terminal.Gui.MenuItem();
            this.exitMenuItem.Title = "Exit";
            this.exitMenuItem.Data = "exitMenuItem";
            this.fileF9Menu.Children = new Terminal.Gui.MenuItem[] {
                    this.saveAsMenuItem,
                    this.refreshMenuItem,
                    this.exitMenuItem};
            this.testMenu = new Terminal.Gui.MenuBarItem();
            this.testMenu.Title = "Test";
            this.createTestDocumentsMenuItem = new Terminal.Gui.MenuItem();
            this.createTestDocumentsMenuItem.Title = "Create Test Documents";
            this.createTestDocumentsMenuItem.Data = "createTestDocumentsMenuItem";
            this.createTestNestedDocumentsMenuItem = new Terminal.Gui.MenuItem();
            this.createTestNestedDocumentsMenuItem.Title = "Create Test Nested Documents";
            this.createTestNestedDocumentsMenuItem.Data = "createTestNestedDocumentsMenuItem";
            this.testMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.createTestDocumentsMenuItem,
                    this.createTestNestedDocumentsMenuItem};
            this.menuBar.Menus = new Terminal.Gui.MenuBarItem[] {
                    this.fileF9Menu,
                    this.testMenu};
            this.Add(this.menuBar);
        }
    }
}
