
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace nfirestore_cli {
    using Google.Cloud.Firestore;
    using System;
    using Terminal.Gui;
    
    
    public partial class NavigationPane {
        public FirestoreDb Db { get; private set; }

        public MainWindow MainWindow { get; }

        public NavigationPane(MainWindow mainWindow) {
            InitializeComponent();

            tfLookup.KeyDown += TextField_KeyDown;
            MainWindow = mainWindow;
        }

        private void TextField_KeyDown(object sender, Key e)
        {
            if (e.KeyCode == Key.Enter && !e.Handled)
            {
                MainWindow.ShowDocument(tfLookup.Text);
            }
        }


        public void RefreshTree()
        {
            if (Db == null)
            {
                return;
            }
            try
            {
                treeView1.ClearObjects();
                var collections = Db.ListRootCollectionsAsync().ToArrayAsync().Result;
                if (collections.Length > 0)
                {
                    treeView1.AddObjects(collections);
                }
            }
            catch (Exception ex)
            {
                MainWindow.ShowException(ex);
            }
        }

        internal void SetDatabase(Options options)
        {

            try
            {

                var factory = new DatabaseFactory();
                this.Db = factory.Create(options);

                treeView1.TreeBuilder = new FirestoreTreeBuilder(this.Db, options.Limit);
                treeView1.AspectGetter = FirestoreTreePresenter.AspectGetter;
                treeView1.SelectionChanged += TlvObjects_SelectionChanged;
                treeView1.KeyUp += TreeView1_KeyUp;

                RefreshTree();
            }
            catch (Exception ex)
            {
                MessageBox.ErrorQuery("Error Loading",ex.Message, "Close");
            }
        }

        private void TreeView1_KeyUp(object sender, Key e)
        {
            if(e.KeyCode == KeyCode.Enter && !e.Handled)
            {
                if (treeView1.SelectedObject is DocumentReference dr)
                {
                    MainWindow.ShowDocument(dr, true);
                }

                if (treeView1.SelectedObject is CollectionReference cr)
                {
                    MainWindow.OpenCollection(cr, treeView1.TreeBuilder.GetChildren(cr).OfType<DocumentReference>());
                }
            }
        }

        private void TlvObjects_SelectionChanged(object sender, SelectionChangedEventArgs<object> e)
        {
            if (treeView1.SelectedObject is DocumentReference dr)
            {
                MainWindow.ShowDocument(dr, false);
            }
        }
    }
}
