
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace nfirestore_cli {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class TabsPane : Terminal.Gui.View {
        
        private Terminal.Gui.TabView tabView;
        
        private Terminal.Gui.TextView currentDocumentTextView;
        
        private void InitializeComponent() {
            this.currentDocumentTextView = new Terminal.Gui.TextView();
            this.tabView = new Terminal.Gui.TabView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.tabView.Width = Dim.Fill(0);
            this.tabView.Height = Dim.Fill(0);
            this.tabView.X = 0;
            this.tabView.Y = 0;
            this.tabView.Visible = true;
            this.tabView.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.tabView.CanFocus = true;
            this.tabView.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.tabView.Data = "tabView";
            this.tabView.TextAlignment = Terminal.Gui.Alignment.Start;
            this.tabView.MaxTabTextWidth = 30u;
            this.tabView.Style.ShowBorder = false;
            this.tabView.Style.ShowTopLine = false;
            this.tabView.Style.TabsOnBottom = false;
            Terminal.Gui.Tab tabViewselected;
            tabViewselected = new Terminal.Gui.Tab();
            tabViewselected.DisplayText = "<Selected>";
            tabViewselected.View = new View();
            tabViewselected.View.Width = Dim.Fill();
            tabViewselected.View.Height = Dim.Fill();
            this.currentDocumentTextView.Width = Dim.Fill(0);
            this.currentDocumentTextView.Height = Dim.Fill(0);
            this.currentDocumentTextView.X = 0;
            this.currentDocumentTextView.Y = 0;
            this.currentDocumentTextView.Visible = true;
            this.currentDocumentTextView.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.currentDocumentTextView.CanFocus = true;
            this.currentDocumentTextView.ShadowStyle = Terminal.Gui.ShadowStyle.None;
            this.currentDocumentTextView.AllowsTab = true;
            this.currentDocumentTextView.AllowsReturn = true;
            this.currentDocumentTextView.WordWrap = false;
            this.currentDocumentTextView.Data = "currentDocumentTextView";
            this.currentDocumentTextView.Text = "";
            this.currentDocumentTextView.TextAlignment = Terminal.Gui.Alignment.Start;
            tabViewselected.View.Add(this.currentDocumentTextView);
            tabView.AddTab(tabViewselected, false);
            this.tabView.ApplyStyleChanges();
            this.Add(this.tabView);
        }
    }
}
